//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillManagerWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string InformationName { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
